version: '3.9'

services:
  deno:
    build:
      context: ./codes/deno
      target: dev
    env_file:
      - .env
    ports:
      - 8080:8000
    volumes:
      - ./codes/deno:/app

  go:
    build:
      context: ./codes/go
    env_file:
      - .env
    ports:
      - 8081:8080

  java:
    build:
      context: ./codes/java
      target: dev
    env_file:
      - .env
    ports:
      - 8082:8080
    volumes:
      - ./codes/java:/app

  javascript:
    image: node:21-alpine
    command: ['yarn', 'start:dev']
    working_dir: /app
    user: node
    env_file:
      - .env
    ports:
      - 8083:8080
    volumes:
      - ./codes/javascript:/app

  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
  nginx:
    image: nginx:1.24-alpine-slim
    ports:
      - 8084:80
    volumes:
      - ./codes/php/public/:/var/www/html/public/
      - ./codes/php/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  
  php:
    build:
      context: ./codes/php
      target: dev
    env_file:
      - .env
      - ./codes/php/.env
    volumes:
      - ./codes/php/:/var/www/html

