version: '3.9'

services:
  deno:
    build:
      context: ./codes/deno
      target: dev
    env_file:
      - .env
    ports:
      - 8080:8000
    volumes:
      - ./codes/deno:/app

  go:
    build:
      context: ./codes/go
    env_file:
      - .env
    ports:
      - 8081:8080

  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
